name: Update LDraw

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC

jobs:
  update:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        ref: 'ldraw'
        fetch-depth: 0

    - name: Checkout BrickStore
      run: |
        echo -n "Downloading latest script and mappings..."
        mkdir -p ldraw-temp
        cd ldraw-temp
        git clone --depth 1 --filter=blob:none --sparse https://github.com/rgriebl/brickstore.git
        cd brickstore
        git sparse-checkout set --no-cone /ldraw
        cd ..
        cd ..
        echo "done"
      shell: bash

    - name: Update Mappings
      run: |
        ./ldraw-temp/brickstore/ldraw/create-bricklink-ldraw-id-mappings.py -t ldraw-temp -a ldraw-temp/brickstore/ldraw/mappings -o ldra

    - name: Commiting changes
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add ldraw/complete.zip
        git status
        if [ -n "$(git status --porcelain)" ]; then
          git commit --amend -m "LDraw update on $(date)"
          git push --force origin HEAD:ldraw
        fi
      shell: bash
